spring:
  application:
    name: shipping-service
  profiles: shipping-service-1
server:
  port: 8380
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # unsafe!
        include: '*'

---

spring:
  application:
    name: shipping-service
  profiles: shipping-service-2
server:
  port: 8381
eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # unsafe!
        include: '*'