spring:
  application:
    name: shipping-service
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        # unsafe!
        include: '*'
